export const sampleExercises = [
  {
    id: "0037",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    focus: "Bounce",
    sets: "3",
    difficulty: "Moderate",
    type: "Adaptability",
    "video_#": "2 (Sat)",
    secondary_position: "N/A",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    common_name: "Wedged Big Toe Extension Bounce, Arm Straight",
    category: "Coordination",
    arm: "Neutal to Bounce",
    strict_name: "Toe Coordination",
    primary_position: "Staggered Stance",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up straight, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    nonce: "1xQdWCzB21PIDcea",
    file_id: "1283",
    body_part: ["toes"],
    primary_joint_anatomical: "Metatarsalphalangeal",
    secondary_movement: "Multi",
    planes_of_movement: "Triplanar",
    primary_movement: "Extension",
    hold: "-",
    equipment: "Wedge",
    original_name:
      "Wedge Assisted Big Toe Extension - opposite side forward/up reach ",
    reps: "12",
    primary_musculature: "Toe Flexors ",
    in_out_of_pattern: "In",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
  },
  {
    id: "0049",
    primary_musculature: "Quadriceps",
    original_name: "Wedged heel squats with Absorb arms",
    planes_of_movement: "Sagittal ",
    secondary_position: "N/A",
    type: "Strength",
    file_id: "1297",
    category: "Bodyweight",
    strict_name: "Upper Leg (Quad) Bodyweight",
    primary_joint_anatomical: "Knee",
    "video_#": "2 (Sat)",
    arm: "In Absorb ",
    hold: "-",
    primary_position: "Parallel Stance",
    benefit:
      "The wedge allows for more depth in your squat by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    start_position:
      "Stand with your feet shoulder-width apart and position a wedge under the heels of both feet",
    secondary_movement: "Dorsiflexion",
    sets: "3",
    reps: "8",
    primary_movement: "Flexion",
    in_out_of_pattern: "In",
    nonce: "2S8qe3vXiyHAoS5H",
    difficulty: "Moderate",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    common_name: "Wedged Heel Squats Absorb Arms",
    body_part: ["quads"],
    equipment: "Wedge",
    movement:
      "Bend your knees to lower your body down as if you are about to sit back into a chair. Use your thigh muscles to push back up into the start position.",
    focus: "Absorb",
  },
  {
    id: "0034",
    primary_position: "Staggered Stance",
    common_name: "Wedged Supination Bounce, Arm 45 Reach, Opposite Pattern",
    primary_musculature: "Foot Intrinsics ",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up on a 45deg angle, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    planes_of_movement: "Triplanar",
    hold: "-",
    reps: "12",
    primary_joint_anatomical: "Foot",
    sets: "3",
    difficulty: "Moderate",
    body_part: ["arch"],
    primary_movement: "Supination",
    file_id: "1279",
    strict_name: "Arch Coordination",
    "video_#": "2 (Sat)",
    focus: "Bounce",
    category: "Coordination",
    secondary_movement: "Multi",
    arm: "N/A",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    in_out_of_pattern: "Out",
    equipment: "Wedge",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    nonce: "59BMGWwAR4yLGH4e",
    type: "Adaptability",
    secondary_position: "N/A",
    original_name: "Wedge Assisted Supination - same side 45 degrees/up reach",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
  },
  {
    id: "0048",
    planes_of_movement: "Sagittal ",
    "video_#": "2 (Sat)",
    arm: "N/A",
    secondary_position: "N/A",
    type: "Strength",
    in_out_of_pattern: "Out",
    file_id: "1295",
    strict_name: "Lower Leg (Calf) Bodyweight",
    movement:
      "Lift your heel as high as you can can and return back to neutral",
    benefit:
      "The wedge provides an external source of force that will challenge your ankle ROM. This increases the ROM available at the ankle in a running gait ",
    sets: "3",
    primary_movement: "Plantarflexion",
    focus: "Bounce",
    secondary_movement: "Extension",
    equipment: "Wedge",
    primary_position: "Single Leg Stance",
    category: "Bodyweight",
    nonce: "6YVxooK5joLZ4QBf",
    primary_musculature: "Gastrocnemius ",
    common_name: "Wedged Single Heel Raise",
    start_position: "Single leg standing with wedge under front of foot. ",
    difficulty: "Moderate",
    hold: "-",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    original_name: "Wedged Single Heel Raise",
    reps: "8",
    primary_joint_anatomical: "Talocural ",
    body_part: ["calf"],
  },
  {
    id: "0017",
    primary_movement: "Dorsiflexion",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    "video_#": "2 (Sat)",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - opposite side, forward reach",
    in_out_of_pattern: "In",
    strict_name: "Ankle Coordination",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    nonce: "7xKiI0MX8fmyvDeM",
    hold: "-",
    common_name: "Wedged Dorsiflexion Absorb, Arm Straight",
    arm: "Neutral to Absorb",
    planes_of_movement: "Triplanar",
    primary_joint_anatomical: "Talocural ",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    difficulty: "Moderate",
    focus: "Absorb",
    sets: "3",
    category: "Coordination",
    file_id: "1262",
    secondary_position: "N/A",
    type: "Adaptability",
    primary_position: "Staggered Stance",
    movement:
      "Reach the arm of the opposite side as your front foot striaght forward. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    reps: "12",
    body_part: ["ankle"],
    secondary_movement: "Multi",
    primary_musculature: "Gastrocnemius ",
    equipment: "Wedge",
  },
  {
    id: "0045",
    body_part: ["ankle"],
    start_position:
      "In a staggered position with a wedge underneath under the front foot.",
    primary_musculature: "Tibialis Anterior",
    reps: "12",
    primary_joint_anatomical: "Talocural ",
    category: "Coordination",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the dorsiflexion movement of the foot. This increases the ROM available at the ankle when in a running gait. ",
    strict_name: "Ankle Coordination",
    sets: "3",
    focus: "Absorb",
    movement:
      "Perform a absorb motion onto front foot with the opposite arm reaching forward and same side arm extending backwards",
    common_name: "Wedged foot transverse reaches",
    equipment: "Wedge",
    arm: "In Absorb ",
    difficulty: "Advanced",
    additional_details: "Take breaks as needed",
    primary_movement: "Multi",
    hold: "-",
    file_id: "1291",
    planes_of_movement: "Triplanar",
    "video_#": "2 (Sat)",
    original_name: "Wedged foot transverse reaches",
    type: "Adaptability",
    primary_position: "Staggered Stance",
    nonce: "99r9crJ5FHCI6WFn",
    in_out_of_pattern: "In",
    secondary_position: "N/A",
    secondary_movement: "Dorsiflexion",
  },
  {
    id: "0004",
    common_name: "Alternating Toe Extensions",
    secondary_position: "N/A",
    strict_name: "Toe Coordination",
    primary_joint_anatomical: "Metatarsalphalangeal",
    body_part: ["toes"],
    hold: "-",
    primary_movement: "Extension",
    sets: "3",
    file_id: "1248",
    in_out_of_pattern: "Out",
    primary_musculature: "Toe Extensors ",
    movement:
      "Alternate between lifting your big toe up and your small toes up.",
    start_position: "Standing feet shoulder-width apart. ",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    primary_position: "Parallel Stance",
    "video_#": "2 (Sat)",
    additional_details:
      "Maintain balance and control with the rest of the foot. ",
    secondary_movement: "N/A",
    planes_of_movement: "Sagittal ",
    nonce: "9hrH3E18M0RrWWoZ",
    original_name: "Alternating Toe Extensions",
    category: "Coordination",
    difficulty: "Moderate",
    focus: "Bounce",
    arm: "N/A",
    equipment: "No Equipment",
    type: "Adaptability",
    reps: "12",
  },
  {
    id: "0032",
    category: "Coordination",
    difficulty: "Advanced",
    sets: "3",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    "video_#": "2 (Sat)",
    planes_of_movement: "Triplanar",
    in_out_of_pattern: "In",
    strict_name: "Arch Coordination",
    focus: "Bounce",
    file_id: "1277",
    primary_joint_anatomical: "Foot",
    common_name:
      "Wedged Supination with opposite side, med ball reach 45 degrees",
    type: "Adaptability",
    reps: "12",
    primary_position: "Staggered Stance",
    primary_movement: "Supination",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    hold: "-",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    nonce: "CB5h4fpF6T1kGH67",
    secondary_movement: "Multi",
    equipment: "Wedge & Weight",
    arm: "Neutal to Bounce",
    original_name:
      "Wedge Assisted Supination - opposite side, med ball reach 45 degrees",
    body_part: ["arch"],
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach your arms and the weight up on a 45deg angle across your body toward the front leg. Return to neutral and repeat",
    secondary_position: "N/A",
    primary_musculature: "Foot Intrinsics ",
  },
  {
    id: "0046",
    original_name: "Wedged heel transverse reaches",
    secondary_position: "N/A",
    sets: "3",
    reps: "12",
    file_id: "1292",
    category: "Coordination",
    focus: "Absorb",
    start_position:
      "In a staggered position with a wedge underneath under the front heel.",
    primary_position: "Staggered Stance",
    nonce: "DBs0NriumIP3cxII",
    strict_name: "Ankle Coordination",
    arm: "In Absorb ",
    body_part: ["ankle"],
    type: "Adaptability",
    equipment: "Wedge",
    "video_#": "2 (Sat)",
    hold: "-",
    common_name: "Wedged heel transverse reaches",
    primary_musculature: "Gastrocnemius ",
    additional_details: "Take breaks as needed",
    movement:
      "Perform an absorb motion onto front foot with the opposite arm reaching forward and same side arm extending backwards",
    planes_of_movement: "Triplanar",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the dorsiflexion movement of the foot. This increases the ROM available at the ankle when in a running gait. ",
    secondary_movement: "Plantarflexion",
    in_out_of_pattern: "In",
    primary_joint_anatomical: "Talocural ",
    difficulty: "Advanced",
    primary_movement: "Multi",
  },
  {
    id: "0041",
    sets: "3",
    equipment: "Wedge",
    hold: "-",
    secondary_position: "N/A",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    focus: "Bounce",
    secondary_movement: "Multi",
    difficulty: "Moderate",
    reps: "12",
    in_out_of_pattern: "Out",
    category: "Coordination",
    primary_position: "Staggered Stance",
    common_name:
      "Wedged Big Toe Extension Bounce, Arm Straight, Opposite Pattern",
    arm: "N/A",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up straight, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    primary_movement: "Extension",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    "video_#": "2 (Sat)",
    primary_musculature: "Toe Flexors ",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    planes_of_movement: "Triplanar",
    original_name:
      "Wedge Assisted Big Toe Extension - same side forward/up reach ",
    primary_joint_anatomical: "Metatarsalphalangeal",
    nonce: "DpsSQs5OdqGOIXQa",
    type: "Adaptability",
    file_id: "1287",
    strict_name: "Toe Coordination",
    body_part: ["toes"],
  },
  {
    id: "0027",
    file_id: "1272",
    primary_position: "Staggered Stance",
    primary_joint_anatomical: "Foot",
    movement:
      "Reach the arm of the opposite side as your front foot 90deg across your body toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight.",
    primary_movement: "Pronation",
    hold: "-",
    arm: "Neutral to Absorb",
    sets: "3",
    secondary_movement: "Multi",
    planes_of_movement: "Triplanar",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    secondary_position: "N/A",
    original_name: "Wedge Assisted Pronation - opposite side, 90 degree reach",
    equipment: "Wedge",
    strict_name: "Arch Coordination",
    common_name: "Wedged Pronation Absorb, Arm 90 Reach",
    body_part: ["arch"],
    difficulty: "Moderate",
    nonce: "E3MBODkSMojhvM3c",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    in_out_of_pattern: "In",
    focus: "Absorb",
    category: "Coordination",
    reps: "12",
    "video_#": "2 (Sat)",
    type: "Adaptability",
    primary_musculature: "Foot Intrinsics ",
  },
  {
    id: "0050",
    "video_#": "2 (Sat)",
    primary_joint_anatomical: "Knee",
    primary_movement: "Flexion",
    file_id: "1298",
    secondary_position: "N/A",
    arm: "N/A",
    focus: "Absorb",
    original_name: "Wedged Pistol Squat ",
    secondary_movement: "Dorsiflexion",
    nonce: "EBiHKmaAzcHhgkAF",
    in_out_of_pattern: "Out",
    benefit:
      "The wedge allows for more depth in your squat by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    common_name: "Wedged Pistol Squat",
    reps: "8",
    strict_name: "Upper Leg (Quad) Bodyweight",
    additional_details:
      "No Wedge? Try using a rolled towel instead. Elevated heels help to place more emphasis on the front of thigh muscles, and gives access to greater ankle ROM.",
    primary_musculature: "Quadriceps",
    hold: "-",
    sets: "3",
    body_part: ["quads"],
    start_position:
      "Position a wedge under the heel of one of your feet, then stand in a single leg position ontop the wedge. ",
    type: "Strength",
    difficulty: "Advanced",
    category: "Bodyweight",
    movement:
      "Slowly lower your body down, bending your knee, while sticking the other leg straight out in front of you. Picture sitting down on an invisible chair. Then, push through the heel of your standing foot to rise back up to the starting position.",
    equipment: "Wedge",
    planes_of_movement: "Sagittal ",
    primary_position: "Single Leg Stance",
  },
  {
    id: "0025",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    in_out_of_pattern: "In",
    category: "Coordination",
    movement:
      "Reach the arm of the opposite side as your front foot striaght forward. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    sets: "3",
    difficulty: "Moderate",
    secondary_position: "N/A",
    nonce: "F75RhIEgHPpzyHBa",
    primary_joint_anatomical: "Foot",
    original_name: "Wedge Assisted Pronation - opposite side, forward reach",
    "video_#": "2 (Sat)",
    type: "Adaptability",
    hold: "-",
    file_id: "1270",
    common_name: "Wedged Pronation Absorb, Arm Straight",
    secondary_movement: "Multi",
    primary_musculature: "Foot Intrinsics ",
    planes_of_movement: "Triplanar",
    primary_position: "Staggered Stance",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    arm: "Neutral to Absorb",
    reps: "12",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    equipment: "Wedge",
    focus: "Absorb",
    strict_name: "Arch Coordination",
    body_part: ["arch"],
    primary_movement: "Pronation",
  },
  {
    id: "0033",
    strict_name: "Arch Coordination",
    original_name: "Wedge Assisted Supination - same side forward/up reach ",
    secondary_movement: "Multi",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    primary_movement: "Supination",
    focus: "Bounce",
    category: "Coordination",
    body_part: ["arch"],
    common_name: "Wedged Supination Bounce, Arm Straight, Opposite Pattern",
    reps: "12",
    nonce: "HrhztJK6WYdRN3Nj",
    hold: "-",
    secondary_position: "N/A",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    primary_musculature: "Foot Intrinsics ",
    type: "Adaptability",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    difficulty: "Moderate",
    file_id: "1278",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up straight, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    arm: "N/A",
    primary_position: "Staggered Stance",
    "video_#": "2 (Sat)",
    primary_joint_anatomical: "Foot",
    planes_of_movement: "Triplanar",
    in_out_of_pattern: "Out",
    sets: "3",
    equipment: "Wedge",
  },
  {
    id: "0005",
    secondary_position: "N/A",
    focus: "Absorb",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    equipment: "Towel",
    secondary_movement: "Supination",
    nonce: "IMIjukce8qbr0WyK",
    planes_of_movement: "Sagittal ",
    primary_musculature: "Toe Flexors ",
    arm: "N/A",
    common_name: "Foot Towel Scrunch",
    hold: "-",
    "video_#": "2 (Sat)",
    difficulty: "Beginner",
    start_position:
      "Standing feet shoulder-width apart. Place a towel under your foot. ",
    additional_details: "Take breaks as needed. ",
    category: "Resistance",
    strict_name: "Arch Resistance",
    primary_position: "Parallel Stance",
    primary_movement: "Flexion",
    type: "Strength",
    original_name: "towel scrunches",
    reps: "8",
    primary_joint_anatomical: "Foot",
    sets: "3",
    in_out_of_pattern: "Out",
    body_part: ["arch"],
    movement:
      "Using the muscles within your foot, bend your toes to grab and scrunch the towel.",
    file_id: "1257",
  },
  {
    id: "0009",
    file_id: "1252",
    primary_position: "Parallel Stance",
    difficulty: "Beginner",
    primary_musculature: "Toe Extensors ",
    secondary_position: "N/A",
    sets: "3",
    hold: "-",
    start_position:
      "In a staggered stance, lift the front foot up from the ground while keeping heel in contact with the floor. ",
    planes_of_movement: "Sagittal + Frontal ",
    secondary_movement: "Dorsiflexion",
    arm: "N/A",
    additional_details:
      "Can also try keeping the rest of your foot on the ground to challenge your foot control. ",
    in_out_of_pattern: "Out",
    common_name: "Toe Spreading",
    equipment: "No Equipment",
    focus: "Bounce",
    strict_name: "Toe Mobility",
    "video_#": "2 (Sat)",
    nonce: "JX7mT3yLXDjSkUtT",
    primary_joint_anatomical: "Metatarsalphalangeal",
    type: "Flexibility ",
    movement: "Using the muscles within your foot, spread your toes apart. ",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    primary_movement: "Extension",
    reps: "10",
    category: "Mobility",
    original_name: "Toe Spreading",
    body_part: ["toes"],
  },
  {
    id: "0007",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    body_part: ["toes"],
    category: "Coordination",
    movement: "Raise your small toes up into the air",
    secondary_position: "N/A",
    planes_of_movement: "Sagittal ",
    reps: "12",
    in_out_of_pattern: "Out",
    common_name: "Small Toes Extension",
    primary_movement: "Extension",
    primary_musculature: "Toe Extensors ",
    primary_position: "Parallel Stance",
    nonce: "KoFwLC16Lbp1TROf",
    additional_details:
      "Maintain balance and control with the rest of the foot. ",
    type: "Adaptability",
    difficulty: "Moderate",
    focus: "Bounce",
    secondary_movement: "N/A",
    "video_#": "2 (Sat)",
    primary_joint_anatomical: "Metatarsalphalangeal",
    original_name: "Small Toes Extension",
    start_position: "Standing feet shoulder-width apart. ",
    hold: "-",
    arm: "N/A",
    strict_name: "Toe Coordination",
    sets: "3",
    file_id: "1250",
    equipment: "No Equipment",
  },
  {
    id: "0043",
    type: "Adaptability",
    body_part: ["toes"],
    focus: "Bounce",
    nonce: "MSL1SOzg47sySNmd",
    primary_joint_anatomical: "Metatarsalphalangeal",
    file_id: "1289",
    sets: "3",
    planes_of_movement: "Triplanar",
    "video_#": "2 (Sat)",
    in_out_of_pattern: "Out",
    common_name: "Wedged Big Toe Extension Bounce, Arm 90, Opposite Pattern",
    arm: "N/A",
    primary_musculature: "Toe Flexors ",
    secondary_position: "N/A",
    strict_name: "Toe Coordination",
    hold: "-",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    secondary_movement: "Multi",
    difficulty: "Moderate",
    category: "Coordination",
    original_name:
      "Wedge Assisted Big Toe Extension - same side 90 degrees/up reach",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up on a 90deg angle, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    reps: "12",
    primary_movement: "Extension",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    equipment: "Wedge",
    primary_position: "Staggered Stance",
  },
  {
    id: "0011",
    primary_movement: "Supination",
    reps: "8",
    primary_joint_anatomical: "Foot",
    file_id: "1254",
    strict_name: "Arch Bodyweight",
    movement:
      "While maintaining 3 points of contact on the ground, engage the muscles within your foot to raise the inside arch.",
    body_part: ["arch"],
    secondary_movement: "Flexion",
    start_position:
      "In a staggered stance with weight slightly shifted to the front leg with 3 points of contact between foot and ground. ",
    "video_#": "2 (Sat)",
    secondary_position: "N/A",
    equipment: "No Equipment",
    sets: "3",
    planes_of_movement: "Sagittal ",
    type: "Strength",
    difficulty: "Moderate",
    additional_details:
      "Maintain three primary points of the back foot: big toe, baby toe and middle of your heel. ",
    primary_musculature: "Foot Intrinsics ",
    nonce: "N28hOhvfXQVA8Cq9",
    hold: "-",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    original_name: "Standing Arch intrinsics lift ",
    primary_position: "Staggered Stance",
    in_out_of_pattern: "Out",
    arm: "N/A",
    category: "Bodyweight",
    common_name: "Arch Intrinsics Lift",
    focus: "Bounce",
  },
  {
    id: "0010",
    equipment: "No Equipment",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    strict_name: "Toe Bodyweight",
    primary_joint_anatomical: "Metatarsalphalangeal",
    category: "Bodyweight",
    reps: "8",
    hold: "-",
    difficulty: "Beginner",
    start_position: "Standing feet shoulder-width apart. ",
    body_part: ["toes"],
    primary_movement: "Extension",
    original_name: "Great toe extension ",
    file_id: "1253",
    primary_position: "Parallel Stance",
    additional_details:
      "Maintain balance and control with the rest of the foot. ",
    arm: "N/A",
    movement: "Raise great toe up into the air. ",
    sets: "3",
    secondary_movement: "N/A",
    type: "Strength",
    secondary_position: "N/A",
    planes_of_movement: "Sagittal ",
    nonce: "SbxMTwraaH7Lrg6k",
    focus: "Bounce",
    "video_#": "2 (Sat)",
    in_out_of_pattern: "Out",
    common_name: "Great toe extension ",
    primary_musculature: "Toe Extensors ",
  },
  {
    id: "0023",
    reps: "12",
    in_out_of_pattern: "Out",
    secondary_position: "N/A",
    strict_name: "Arch Coordination",
    category: "Coordination",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    type: "Adaptability",
    arm: "N/A",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    file_id: "1268",
    nonce: "VMhAb2SpHaOvxSNz",
    planes_of_movement: "Triplanar",
    difficulty: "Moderate",
    hold: "-",
    original_name: "Wedge Assisted Pronation - same side, 90 degree reach",
    focus: "Absorb",
    movement:
      "Reach the arm of the same side as your front foot 90deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    body_part: ["arch"],
    common_name: "Wedged Pronation Absorb, Arm 90 Reach, Opposite Pattern",
    primary_musculature: "Foot Intrinsics ",
    primary_movement: "Pronation",
    primary_joint_anatomical: "Foot",
    sets: "3",
    secondary_movement: "Multi",
    equipment: "Wedge",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    primary_position: "Staggered Stance",
    "video_#": "2 (Sat)",
  },
  {
    id: "0008",
    additional_details: "Use enough force to feel a gentle stretch.",
    primary_joint_anatomical: "Metatarsalphalangeal",
    reps: "4",
    in_out_of_pattern: "Out",
    original_name: "Big toe Flexion stretch",
    primary_musculature: "Toe Extensors ",
    nonce: "WhWDRpe6GLc5LHcr",
    primary_position: "Parallel Stance",
    difficulty: "Beginner",
    primary_movement: "Flexion",
    strict_name: "Toe Stretch",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    secondary_movement: "Flexion",
    secondary_position: "N/A",
    body_part: ["toes"],
    common_name: "Big toe Flexion stretch",
    sets: "1",
    movement:
      "Bend your big toe down toward the ground and apply light pressure with the rest of your foot. Should feel a stretch along the top of your big toe. ",
    "video_#": "2 (Sat)",
    hold: "30",
    file_id: "1251",
    type: "Flexibility ",
    planes_of_movement: "Sagittal ",
    category: "Stretch",
    start_position: "Standing feet shoulder-width apart. ",
    arm: "N/A",
    focus: "Bounce",
    equipment: "No Equipment",
  },
  {
    id: "0014",
    sets: "3",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    primary_musculature: "Gastrocnemius ",
    in_out_of_pattern: "Out",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - same side, 45 degree reach",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    difficulty: "Moderate",
    planes_of_movement: "Triplanar",
    type: "Adaptability",
    primary_position: "Staggered Stance",
    equipment: "Wedge",
    common_name: "Wedged Dorsiflexion Absorb, Arm 45 Reach, Opposite Pattern",
    category: "Coordination",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    secondary_movement: "Multi",
    reps: "12",
    file_id: "1259",
    primary_movement: "Dorsiflexion",
    body_part: ["ankle"],
    nonce: "Y1J1Ag30bFgptiDS",
    focus: "Absorb",
    hold: "-",
    primary_joint_anatomical: "Talocural ",
    "video_#": "2 (Sat)",
    arm: "N/A",
    movement:
      "Reach the arm of the same side as your front foot 45deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    secondary_position: "N/A",
    strict_name: "Ankle Coordination",
  },
  {
    id: "0012",
    file_id: "1255",
    primary_movement: "Abduction",
    secondary_position: "N/A",
    movement:
      "Use your leg to pull away from the great toe. Feeling a stretch on the inside of your great toe. ",
    primary_position: "Staggered Stance",
    additional_details: "Use enough force to feel a gentle stretch. ",
    "video_#": "2 (Sat)",
    sets: "1",
    reps: "4",
    strict_name: "Toe Stretch",
    start_position:
      "Standing with one foot toe pointed, with the end of your big toe touching the ground. ",
    difficulty: "Beginner",
    category: "Stretch",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    in_out_of_pattern: "Out",
    original_name: "Big Toe Abduction Stretch",
    planes_of_movement: "Frontal ",
    body_part: ["toes"],
    nonce: "YVZxTDfyQgWqpoFV",
    hold: "30",
    primary_joint_anatomical: "Metatarsalphalangeal",
    secondary_movement: "N/A",
    primary_musculature: "N/A",
    focus: "Bounce",
    arm: "N/A",
    equipment: "No Equipment",
    type: "Flexibility ",
    common_name: "Big Toe Abduction Stretch",
  },
  {
    id: "0029",
    reps: "12",
    original_name:
      "Wedge Assisted Supination - opposite side forward/up reach ",
    file_id: "1274",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    in_out_of_pattern: "In",
    primary_musculature: "Foot Intrinsics ",
    secondary_position: "N/A",
    common_name: "Wedged Supination Bounce, Arm Straight",
    equipment: "Wedge",
    arm: "Neutal to Bounce",
    nonce: "YjyUJoOwJH7NmH1a",
    body_part: ["arch"],
    planes_of_movement: "Triplanar",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    "video_#": "2 (Sat)",
    focus: "Bounce",
    hold: "-",
    primary_movement: "Supination",
    strict_name: "Arch Coordination",
    difficulty: "Moderate",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up straight, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    category: "Coordination",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    type: "Adaptability",
    sets: "3",
    secondary_movement: "Multi",
    primary_joint_anatomical: "Foot",
    primary_position: "Staggered Stance",
  },
  {
    id: "0035",
    difficulty: "Moderate",
    arm: "N/A",
    nonce: "Z7C4rLOfUv7e88Mu",
    primary_musculature: "Foot Intrinsics ",
    common_name: "Wedged Supination Bounce, Arm 90 Reach, Opposite Pattern",
    equipment: "Wedge",
    original_name: "Wedge Assisted Supination - same side 90 degrees/up reach",
    type: "Adaptability",
    in_out_of_pattern: "Out",
    primary_joint_anatomical: "Foot",
    focus: "Bounce",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up on a 90deg angle, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    category: "Coordination",
    secondary_movement: "Multi",
    "video_#": "2 (Sat)",
    hold: "-",
    body_part: ["arch"],
    reps: "12",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    sets: "3",
    file_id: "1281",
    primary_movement: "Supination",
    planes_of_movement: "Triplanar",
    strict_name: "Arch Coordination",
    primary_position: "Staggered Stance",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    secondary_position: "N/A",
  },
  {
    id: "0039",
    category: "Coordination",
    hold: "-",
    body_part: ["toes"],
    nonce: "ZzB1BQlDHTmhT1Rt",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    equipment: "Wedge",
    common_name: "Wedged Big Toe Extension Bounce, Arm 90 Reach",
    file_id: "1285",
    strict_name: "Toe Coordination",
    "video_#": "2 (Sat)",
    secondary_position: "N/A",
    difficulty: "Moderate",
    reps: "12",
    primary_movement: "Extension",
    primary_joint_anatomical: "Metatarsalphalangeal",
    original_name:
      "Wedge Assisted Big Toe Extension - opposite side 90 degrees/up reach",
    primary_position: "Staggered Stance",
    primary_musculature: "Toe Flexors ",
    focus: "Bounce",
    sets: "3",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up on a 90deg angle across your body, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    type: "Adaptability",
    arm: "Neutal to Bounce",
    planes_of_movement: "Triplanar",
    in_out_of_pattern: "In",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    secondary_movement: "Multi",
  },
  {
    id: "0031",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    primary_joint_anatomical: "Foot",
    planes_of_movement: "Triplanar",
    "video_#": "2 (Sat)",
    equipment: "Wedge",
    focus: "Bounce",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up on a 90deg angle across your body, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    original_name:
      "Wedge Assisted Supination - opposite side 90 degrees/up reach",
    arm: "Neutal to Bounce",
    primary_position: "Staggered Stance",
    body_part: ["arch"],
    sets: "3",
    category: "Coordination",
    primary_musculature: "Foot Intrinsics ",
    in_out_of_pattern: "In",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    common_name: "Wedged Supination with opposite side 90 degrees/up reach",
    secondary_position: "N/A",
    nonce: "akjYq7ZCJaPMonE7",
    file_id: "1276",
    primary_movement: "Supination",
    secondary_movement: "Multi",
    hold: "-",
    strict_name: "Arch Coordination",
    reps: "12",
    type: "Adaptability",
    difficulty: "Moderate",
  },
  {
    id: "0038",
    "video_#": "2 (Sat)",
    arm: "Neutal to Bounce",
    file_id: "1284",
    strict_name: "Toe Coordination",
    equipment: "Wedge",
    secondary_position: "N/A",
    secondary_movement: "Multi",
    type: "Adaptability",
    reps: "12",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    planes_of_movement: "Triplanar",
    primary_position: "Staggered Stance",
    primary_joint_anatomical: "Metatarsalphalangeal",
    sets: "3",
    nonce: "cQRET5wbvLplTEv2",
    difficulty: "Moderate",
    in_out_of_pattern: "In",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up on a 45deg angle across your body, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    primary_musculature: "Toe Flexors ",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    primary_movement: "Extension",
    hold: "-",
    common_name: "Wedged Big Toe Extension Bounce, Arm 45 Reach",
    focus: "Bounce",
    original_name:
      "Wedge Assisted Big Toe Extension - opposite side 45 degrees/up reach",
    category: "Coordination",
    body_part: ["toes"],
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
  },
  {
    id: "0019",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    body_part: ["ankle"],
    equipment: "Wedge",
    category: "Coordination",
    primary_joint_anatomical: "Talocural ",
    type: "Adaptability",
    secondary_movement: "Multi",
    primary_movement: "Dorsiflexion",
    secondary_position: "N/A",
    strict_name: "Ankle Coordination",
    reps: "12",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - opposite side, 90 degree reach",
    primary_musculature: "Gastrocnemius ",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    primary_position: "Staggered Stance",
    movement:
      "Reach the arm of the opposite side as your front foot 90deg across your body toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight.",
    sets: "3",
    in_out_of_pattern: "In",
    "video_#": "2 (Sat)",
    common_name: "Wedged Dorsiflexion Absorb, Arm 90 Reach ",
    difficulty: "Moderate",
    file_id: "1264",
    focus: "Absorb",
    arm: "Neutral to Absorb",
    planes_of_movement: "Triplanar",
    nonce: "d6CYy6fSAnX1Zeyz",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    hold: "-",
  },
  {
    id: "0020",
    primary_movement: "Dorsiflexion",
    difficulty: "Advanced",
    secondary_position: "N/A",
    file_id: "1265",
    hold: "-",
    reps: "12",
    focus: "Absorb",
    nonce: "g9vFw1qlsIuqxoWO",
    strict_name: "Ankle Coordination",
    category: "Coordination",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    common_name: "Wedged Dorsiflexion Absorb, Arm 45 Reach, Loaed",
    in_out_of_pattern: "In",
    primary_musculature: "Gastrocnemius ",
    equipment: "Wedge & Weight",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - opposite side, med ball reach 45 degrees",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    type: "Adaptability",
    sets: "3",
    primary_position: "Staggered Stance",
    movement:
      "Reach your arms and the weight 45deg toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    planes_of_movement: "Triplanar",
    body_part: ["ankle"],
    arm: "N/A",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    secondary_movement: "Multi",
    primary_joint_anatomical: "Talocural ",
    "video_#": "2 (Sat)",
  },
  {
    id: "0021",
    original_name: "Wedged Pronation Absorb, Arm Straight, Opposite Pattern",
    hold: "-",
    secondary_movement: "Multi",
    primary_position: "Staggered Stance",
    nonce: "gRJC0ZjLX8Ryy73L",
    secondary_position: "N/A",
    planes_of_movement: "Triplanar",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    category: "Coordination",
    difficulty: "Moderate",
    in_out_of_pattern: "Out",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    equipment: "Wedge",
    common_name: "Wedged Pronation Absorb, Arm Straight, Opposite Pattern",
    reps: "12",
    focus: "Absorb",
    primary_joint_anatomical: "Foot",
    primary_musculature: "Foot Intrinsics ",
    file_id: "1266",
    movement:
      "Reach the arm of the same side as your front foot striaght forward. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    primary_movement: "Pronation",
    strict_name: "Arch Coordination",
    body_part: ["arch"],
    arm: "N/A",
    sets: "3",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    "video_#": "2 (Sat)",
    type: "Adaptability",
  },
  {
    id: "0024",
    primary_movement: "Pronation",
    hold: "-",
    equipment: "Wedge & Weight",
    focus: "Absorb",
    arm: "N/A",
    sets: "3",
    primary_position: "Staggered Stance",
    in_out_of_pattern: "Out",
    category: "Coordination",
    "video_#": "2 (Sat)",
    original_name:
      "Wedge Assisted Pronation - same side, med ball reach degrees 45 degrees",
    nonce: "hOwbNXl6xoiEQole",
    strict_name: "Arch Coordination",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    secondary_movement: "Multi",
    movement:
      "Reach your arms and the weight 45deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    secondary_position: "N/A",
    difficulty: "Advanced",
    primary_joint_anatomical: "Foot",
    common_name:
      "Wedged Pronation Absorb, Arm 45 Reach, Opposite Pattern, Loaded",
    primary_musculature: "Foot Intrinsics ",
    reps: "12",
    file_id: "1269",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    body_part: ["arch"],
    type: "Adaptability",
    planes_of_movement: "Triplanar",
  },
  {
    id: "0013",
    secondary_movement: "Multi",
    primary_movement: "Dorsiflexion",
    secondary_position: "N/A",
    strict_name: "Ankle Coordination",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - same side, forward reach",
    reps: "12",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    primary_position: "Staggered Stance",
    "video_#": "2 (Sat)",
    file_id: "1258",
    movement:
      "Reach the arm of the same side as your front foot striaght forward. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    primary_joint_anatomical: "Talocural ",
    primary_musculature: "Gastrocnemius ",
    arm: "N/A",
    nonce: "iBzWuaY0wAkCBPNn",
    focus: "Absorb",
    category: "Coordination",
    type: "Adaptability",
    body_part: ["ankle"],
    in_out_of_pattern: "Out",
    sets: "3",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    equipment: "Wedge",
    difficulty: "Moderate",
    planes_of_movement: "Triplanar",
    common_name: "Wedged Dorsiflexion Absorb, Arm Straight, Opposite Pattern",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    hold: "-",
  },
  {
    id: "0016",
    strict_name: "Ankle Coordination",
    file_id: "1261",
    planes_of_movement: "Triplanar",
    equipment: "Wedge & Weight",
    arm: "N/A",
    primary_joint_anatomical: "Talocural ",
    focus: "Absorb",
    body_part: ["ankle"],
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - same side, med ball reach 45 degrees",
    reps: "12",
    nonce: "kkgtgV8YFaW73PJN",
    sets: "3",
    primary_musculature: "Gastrocnemius ",
    category: "Coordination",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    primary_position: "Staggered Stance",
    movement:
      "Reach your arms and the weight 45deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    in_out_of_pattern: "Out",
    "video_#": "2 (Sat)",
    difficulty: "Advanced",
    secondary_movement: "Multi",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    hold: "-",
    common_name:
      "Wedged Dorsiflexion Absorb, Arm 45 Reach, Opposite Pattern, Loaded",
    type: "Adaptability",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    secondary_position: "N/A",
    primary_movement: "Dorsiflexion",
  },
  {
    id: "0028",
    difficulty: "Advanced",
    reps: "12",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    category: "Coordination",
    arm: "N/A",
    primary_musculature: "Foot Intrinsics ",
    hold: "-",
    primary_position: "Staggered Stance",
    planes_of_movement: "Triplanar",
    file_id: "1273",
    secondary_position: "N/A",
    equipment: "Wedge & Weight",
    in_out_of_pattern: "In",
    sets: "3",
    strict_name: "Arch Coordination",
    secondary_movement: "Multi",
    primary_movement: "Pronation",
    "video_#": "2 (Sat)",
    focus: "Absorb",
    movement:
      "Reach your arms and the weight 45deg toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    common_name: "Wedged Pronation Absorb, Arm 45 Reach, Loaded",
    original_name:
      "Wedge Assisted Pronation - opposite side, med ball reach degrees 45 degrees",
    nonce: "lQzESAalzs7FX0Yj",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    body_part: ["arch"],
    primary_joint_anatomical: "Foot",
    type: "Adaptability",
  },
  {
    id: "0026",
    nonce: "lRoZrltvph5Y1wqV",
    file_id: "1271",
    primary_joint_anatomical: "Foot",
    planes_of_movement: "Triplanar",
    type: "Adaptability",
    secondary_position: "N/A",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    difficulty: "Moderate",
    equipment: "Wedge",
    primary_movement: "Pronation",
    common_name: "Wedged Pronation Absorb, Arm 45 Reach,",
    strict_name: "Arch Coordination",
    in_out_of_pattern: "In",
    category: "Coordination",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    original_name: "Wedge Assisted Pronation - opposite side, 45 degree reach",
    hold: "-",
    secondary_movement: "Multi",
    arm: "Neutral to Absorb",
    sets: "3",
    focus: "Absorb",
    movement:
      "Reach the arm of the opposite side as your front foot 45deg across your body toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight.",
    "video_#": "2 (Sat)",
    primary_musculature: "Foot Intrinsics ",
    primary_position: "Staggered Stance",
    reps: "12",
    body_part: ["arch"],
  },
  {
    id: "0053",
    primary_joint_anatomical: "Talocural ",
    original_name: "Wedged Big Toe Kneeling DF Mobility ",
    reps: "10",
    focus: "Absorb",
    nonce: "nFnXn1xG6etMWRBH",
    difficulty: "Moderate",
    secondary_position: "N/A",
    planes_of_movement: "Sagittal ",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    in_out_of_pattern: "Out",
    file_id: "1294",
    movement:
      "Maintain position and bend your ankle forward so that your foot moves closer to your shin. Use your body weight over top to assist. You might feel a stretch in the front of your ankle and lower leg.\n",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    common_name: "Kneeling, Great Toe Extension Wedged, Dorsiflexion Mobility",
    category: "Mobility",
    secondary_movement: "Extension",
    sets: "3",
    arm: "N/A",
    start_position: "Half kneeling position with a wedge under the great toe. ",
    "video_#": "2 (Sat)",
    primary_position: "Half Kneeling",
    body_part: ["toes"],
    hold: "-",
    primary_musculature: "Gastrocnemius ",
    strict_name: "Toe Mobility",
    equipment: "Wedge",
    primary_movement: "Dorsiflexion",
    type: "Flexibility ",
  },
  {
    id: "0040",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe. Holding a weight with both hands. ",
    nonce: "oeD1qgZNK7xdyX9x",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    equipment: "Wedge & Weight",
    difficulty: "Advanced",
    file_id: "1286",
    arm: "Neutal to Bounce",
    strict_name: "Toe Coordination",
    common_name: "Wedged Big Toe Extension Bounce, Arm 90 Reach Loaded",
    primary_movement: "Extension",
    body_part: ["toes"],
    focus: "Bounce",
    reps: "12",
    type: "Adaptability",
    sets: "3",
    secondary_movement: "Multi",
    in_out_of_pattern: "In",
    category: "Coordination",
    primary_position: "Staggered Stance",
    planes_of_movement: "Triplanar",
    secondary_position: "N/A",
    hold: "-",
    primary_joint_anatomical: "Metatarsalphalangeal",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach your arms and the weight up on a 45deg angle across your body toward the front leg. Return to neutral and repeat",
    "video_#": "2 (Sat)",
    original_name:
      "Wedge Assisted Big Toe Extension - opposite side, med ball reach 45 degrees",
    primary_musculature: "Toe Flexors ",
  },
  {
    id: "0022",
    arm: "N/A",
    type: "Adaptability",
    common_name: "Wedged Pronation Absorb, Arm 45 Reach, Opposite Pattern",
    difficulty: "Moderate",
    file_id: "1267",
    reps: "12",
    sets: "3",
    in_out_of_pattern: "Out",
    movement:
      "Reach the arm of the same side as your front foot 45deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    start_position:
      "In a staggered position with a wedge underneath the outside edge of the heel of the front foot. ",
    focus: "Absorb",
    secondary_position: "N/A",
    primary_position: "Staggered Stance",
    equipment: "Wedge",
    nonce: "phW39FIzIMEdNCbg",
    category: "Coordination",
    original_name: "Wedge Assisted Pronation - same side, 45 degree reach",
    primary_joint_anatomical: "Foot",
    hold: "-",
    secondary_movement: "Multi",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    body_part: ["arch"],
    planes_of_movement: "Triplanar",
    primary_musculature: "Foot Intrinsics ",
    "video_#": "2 (Sat)",
    strict_name: "Arch Coordination",
    primary_movement: "Pronation",
    benefit:
      "The wedge provides an external support of assist to your foot into the position of pronation. Pronation is the position your foot nautrally goes into when you make contact with the ground as you run, helping to absorb shock and adapt to different surfaces. ",
  },
  {
    id: "0030",
    category: "Coordination",
    body_part: ["arch"],
    sets: "3",
    secondary_position: "N/A",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the same arm up on a 45deg angle across your body, palm facing back. While your opposite arm extends gently behind your body. Return to neutral and repeat",
    hold: "-",
    equipment: "Wedge",
    reps: "12",
    arm: "Neutal to Bounce",
    difficulty: "Moderate",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    nonce: "qbTgJQUTTGoHzZV7",
    primary_position: "Staggered Stance",
    focus: "Bounce",
    benefit:
      "The wedge provides an external source of support to assist to your foot in the position of supination. Supination helps to distribute the force of impact evenly across your foot, ankle, and leg. It also helps assist in efficient push off resulting in better propulsion forward.",
    file_id: "1275",
    start_position:
      "In a staggered position with a wedge underneath under the back foot's front outside edge. ",
    original_name:
      "Wedge Assisted Supination - opposite side 45 degrees/up reach",
    common_name: "Wedged Supination Bounce, Arm 45 Reach",
    primary_musculature: "Foot Intrinsics ",
    primary_movement: "Supination",
    in_out_of_pattern: "In",
    type: "Adaptability",
    planes_of_movement: "Triplanar",
    secondary_movement: "Multi",
    strict_name: "Arch Coordination",
    primary_joint_anatomical: "Foot",
    "video_#": "2 (Sat)",
  },
  {
    id: "0052",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    original_name: "Sissy Sqaut With Wedge (under forefoot)",
    strict_name: "Upper Leg (Quad) Bodyweight",
    secondary_movement: "Plantarflexion",
    hold: "- ",
    focus: "Absorb",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    nonce: "r22JxXCrAP9d6fhi",
    planes_of_movement: "Sagittal ",
    body_part: ["quads"],
    movement:
      "Rise up onto your toes by lifting your heels. Lean back slightly while bending your knees allowing them to push forward over the toes as you lower your body down as far as you can. You may feel a stretch in your thighs and knees. Straighten your knees and push up using your thigh muscles to return back up to the starting position",
    primary_movement: "Flexion",
    file_id: "1299",
    sets: "3",
    type: "Strength",
    start_position:
      "Stand with your feet shoulder-width apart and position a wedge under the toes of both feet. ",
    secondary_position: "N/A",
    in_out_of_pattern: "Out",
    primary_position: "Parallel Stance",
    category: "Bodyweight",
    "video_#": "2 (Sat)",
    primary_joint_anatomical: "Knee",
    common_name: "Wedged Heel Raise Sissy Squat",
    difficulty: "Advanced",
    primary_musculature: "Quadriceps",
    equipment: "Wedge",
    reps: "8",
    arm: "N/A",
  },
  {
    id: "0015",
    hold: "-",
    in_out_of_pattern: "Out",
    primary_position: "Staggered Stance",
    primary_joint_anatomical: "Talocural ",
    secondary_movement: "Multi",
    equipment: "Wedge",
    secondary_position: "N/A",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    movement:
      "Reach the arm of the same side as your front foot 90deg across your body. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight. ",
    focus: "Absorb",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    category: "Coordination",
    strict_name: "Ankle Coordination",
    planes_of_movement: "Triplanar",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - same side, 90 degree reach",
    "video_#": "2 (Sat)",
    nonce: "s3vq0aVfaJ9l8ocV",
    difficulty: "Moderate",
    sets: "3",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    reps: "12",
    common_name: "Wedged Dorsiflexion Absorb, Arm 90 Reach, Opposite Pattern",
    type: "Adaptability",
    arm: "N/A",
    body_part: ["ankle"],
    file_id: "1260",
    primary_musculature: "Gastrocnemius ",
    primary_movement: "Dorsiflexion",
  },
  {
    id: "0047",
    start_position:
      "Stand with feet shoulder-width apart with a wedge under front of feet. ",
    nonce: "tJenc26FFd0url0b",
    common_name: "Wedged Double Heel Raise",
    primary_position: "Parallel Stance",
    "video_#": "2 (Sat)",
    strict_name: "Lower Leg (Calf) Bodyweight",
    original_name: "Wedged Double Heel Raise",
    secondary_position: "N/A",
    arm: "Hands Across Chest",
    primary_movement: "Plantarflexion",
    file_id: "1293",
    hold: "-",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    in_out_of_pattern: "Out",
    secondary_movement: "Extension",
    type: "Strength",
    reps: "8",
    primary_joint_anatomical: "Talocural ",
    equipment: "Wedge",
    category: "Bodyweight",
    planes_of_movement: "Sagittal ",
    sets: "3",
    focus: "Bounce",
    body_part: ["calf"],
    difficulty: "Beginner",
    benefit:
      "The wedge provides an external source of force that will challenge your ankle ROM. This increases the ROM available at the ankle in a running gait",
    movement:
      "Lift your heels as high as you can can and return back to neutral",
    primary_musculature: "Gastrocnemius ",
  },
  {
    id: "0006",
    primary_musculature: "Hip Extensors",
    secondary_position: "Single Leg Stance",
    secondary_movement: "N/A",
    strict_name: "Buttocks Bodyweight",
    sets: "3",
    original_name: "Straight leg kick backs",
    arm: "N/A",
    "video_#": "2 (Sat)",
    hold: "-",
    primary_position: "Parallel Stance",
    start_position: "Standing feet shoulder-width apart. ",
    body_part: ["buttocks"],
    nonce: "vc9RuFpuJSh3Poeb",
    planes_of_movement: "Sagittal + Frontal ",
    reps: "8",
    primary_joint_anatomical: "Metatarsalphalangeal",
    category: "Bodyweight",
    benefit:
      "Think of your feet as the ground foundation to your body for running. As a runner it is important to ensure quality movement starts from the ground up.",
    in_out_of_pattern: "Out",
    file_id: "1249",
    difficulty: "Moderate",
    movement:
      "Balance on one leg as you raise the other behind you for a small kick. Keep the leg moving behind you straight. ",
    focus: "Absorb",
    type: "Strength",
    primary_movement: "Extension",
    additional_details:
      "Maintain three primary points of the back foot: big toe, baby toe and middle of your heel. ",
    common_name: "Straight leg kick backs",
    equipment: "No Equipment",
  },
  {
    id: "0018",
    additional_details:
      "Take breaks where required. Focus on the arch of your foot getting closer to the ground. ",
    hold: "-",
    equipment: "Wedge",
    body_part: ["ankle"],
    movement:
      "Reach the arm of the opposite side as your front foot 45deg across your body toward your front leg. Lean forward onto front foot and perform pronation motion allowing arch of the foot to shrink under body weight.",
    secondary_movement: "Multi",
    original_name:
      "Wedge Assisted Dorsiflexion / Under Heel - opposite side, 45 degree reach",
    nonce: "w21HwCv5XyPNtMPs",
    start_position:
      "In a staggered position with a wedge underneath the heel of the front foot. ",
    type: "Adaptability",
    in_out_of_pattern: "In",
    primary_joint_anatomical: "Talocural ",
    reps: "12",
    file_id: "1263",
    secondary_position: "N/A",
    "video_#": "2 (Sat)",
    category: "Coordination",
    difficulty: "Moderate",
    arm: "Neutral to Absorb",
    benefit:
      "The wedge provides an external support that allows for more depth into this absorb position by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    primary_musculature: "Gastrocnemius ",
    focus: "Absorb",
    sets: "3",
    planes_of_movement: "Triplanar",
    primary_movement: "Dorsiflexion",
    primary_position: "Staggered Stance",
    common_name: "Wedged Dorsiflexion Absorb, Arm 45 Reach ",
    strict_name: "Ankle Coordination",
  },
  {
    id: "0042",
    category: "Coordination",
    sets: "3",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    original_name:
      "Wedge Assisted Big Toe Extension - same side 45 degrees/up reach",
    strict_name: "Toe Coordination",
    in_out_of_pattern: "Out",
    secondary_position: "N/A",
    nonce: "wZ92TPK2pr5am5JL",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    common_name: "Wedged Big Toe Extension Bounce, Arm 45, Opposite Pattern",
    equipment: "Wedge",
    type: "Adaptability",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach the opposite arm up on a 45deg angle, palm facing back. While the arm (same side as back foot) extends gently behind your body. Return to neutral and repeat.",
    primary_position: "Staggered Stance",
    "video_#": "2 (Sat)",
    reps: "12",
    body_part: ["toes"],
    file_id: "1288",
    primary_joint_anatomical: "Metatarsalphalangeal",
    focus: "Bounce",
    hold: "-",
    arm: "N/A",
    primary_movement: "Extension",
    secondary_movement: "Multi",
    planes_of_movement: "Triplanar",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe.",
    primary_musculature: "Toe Flexors ",
    difficulty: "Moderate",
  },
  {
    id: "0054",
    additional_details: "No Wedge? Try using a rolled towel instead. ",
    category: "Mobility",
    equipment: "Wedge",
    sets: "3",
    arm: "N/A",
    start_position:
      "Half kneeling position with a wedge under he front of the foot. ",
    primary_musculature: "Gastrocnemius ",
    file_id: "1300",
    planes_of_movement: "Sagittal ",
    primary_joint_anatomical: "Talocural ",
    secondary_movement: "N/A",
    primary_movement: "Dorsiflexion",
    strict_name: "Ankle Mobility",
    movement:
      "Maintain position and bend your ankle forward so that your foot moves closer to your shin. Use your body weight over top to assist. You might feel a stretch in the front of your ankle and lower leg.\n",
    difficulty: "Moderate",
    common_name: "Kneeling, Foot Wedged, Dorsiflexion Mobility ",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the dorsiflexion movement of the foot. This increases the ROM available at the foot when in a running gait.",
    hold: "- ",
    focus: "Absorb",
    body_part: ["ankle"],
    in_out_of_pattern: "Out",
    primary_position: "Half Kneeling",
    secondary_position: "N/A",
    nonce: "y16QOCx4ArgDe1FB",
    reps: "10",
    "video_#": "2 (Sat)",
    type: "Flexibility ",
    original_name: "Wedged Half Kneeling Dorsiflexion Mobility",
  },
  {
    id: "0051",
    additional_details:
      "No Wedge? Try using a rolled towel instead. Elevated heels help to place more emphasis on the front of thigh muscles, and gives access to greater ankle ROM.",
    secondary_position: "N/A",
    secondary_movement: "Dorsiflexion",
    sets: "3",
    equipment: "Wedge",
    type: "Strength",
    reps: "8",
    planes_of_movement: "Sagittal ",
    strict_name: "Upper Leg (Quad) Bodyweight",
    focus: "Absorb",
    file_id: "1296",
    category: "Bodyweight",
    difficulty: "Moderate",
    primary_movement: "Flexion",
    nonce: "yQbutZ62WJbMFCoU",
    benefit:
      "The wedge allows for more depth in your squat by increasing the available ankle ROM of Dorsiflexion. This increases the ROM available at the foot in a running gait.",
    primary_musculature: "Quadriceps",
    hold: "- ",
    original_name: "Wedged heel squats ",
    movement:
      "Bend your knees to lower your body down as if you're about to sit back into a chair. Use your thigh muscles to push back up into the start position. ",
    primary_joint_anatomical: "Knee",
    body_part: ["quads"],
    arm: "N/A",
    primary_position: "Parallel Stance",
    in_out_of_pattern: "Out",
    common_name: "Wedged Heel Squats",
    "video_#": "2 (Sat)",
    start_position:
      "Stand with your feet shoulder-width apart and position a wedge under the heels of both feet",
  },
  {
    id: "0044",
    common_name:
      "Wedged Big Toe Extension Bounce, Arm 45 Reach Loaded, Opposite Pattern",
    type: "Adaptability",
    arm: "N/A",
    hold: "-",
    primary_movement: "Extension",
    difficulty: "Advanced",
    sets: "3",
    focus: "Bounce",
    additional_details:
      "Maintain two primary points of the back foot: big toe and baby toe.",
    in_out_of_pattern: "Out",
    secondary_movement: "Multi",
    start_position:
      "In a staggered position with a wedge underneath under the back foot great toe. Holding a weight with both hands. ",
    original_name:
      "Wedge Assisted Big Toe Extension - same side, med ball reach 45 degrees",
    file_id: "1290",
    primary_joint_anatomical: "Metatarsalphalangeal",
    primary_position: "Staggered Stance",
    benefit:
      "The wedge provides a external source of force allowing for an advancement in the extension movement of the toe. This increases the ROM available at the toe for push off when in a running gait.",
    "video_#": "2 (Sat)",
    movement:
      "Put most of your weight on the back leg, using your front leg for support. Lift your back heel by pushing onto your toes. Reach your arms and the weight up on a 45deg angle across your body toward the back leg. Return to neutral and repeat",
    reps: "12",
    primary_musculature: "Toe Flexors ",
    planes_of_movement: "Triplanar",
    secondary_position: "N/A",
    nonce: "zlzdfIv6D1Mw56i1",
    category: "Coordination",
    strict_name: "Toe Coordination",
    body_part: ["toes"],
    equipment: "Wedge & Weight",
  },
];
